"""
make_asoc.py — derive the Applied Soft Computing (Elsevier/elsarticle) manuscript
from the authoritative IJCS source, guaranteeing content parity (no stale numbers).

The IJCS tex body is class-agnostic; only the front matter (sn-jnl -> elsarticle
frontmatter) and the bibliography style change. Run after regenerating the IJCS tex:
    python3 build_paper_ijcs.py   # authoritative content
    python3 make_asoc.py          # -> RG-SCSO_ASOC.tex, _Supplementary.tex, _Highlights.txt
"""
from __future__ import annotations

import re

IJCS_TEX = "RG-SCSO_master.tex"
IJCS_SUPP = "RG-SCSO_master_Supplementary.tex"
OUT_TEX = "RG-SCSO_ASOC.tex"
OUT_SUPP = "RG-SCSO_ASOC_Supplementary.tex"
OUT_HL = "RG-SCSO_ASOC_Highlights.txt"


def _balanced(src: str, start_token: str) -> str:
    """Return the balanced-brace content of e.g. \\abstract{...}."""
    i = src.index(start_token) + len(start_token)
    assert src[i - 1] == "{"
    depth, j = 1, i
    while depth:
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
        j += 1
    return src[i : j - 1]


def build() -> None:
    tex = open(IJCS_TEX).read()

    # --- front matter extraction ---------------------------------------
    title = _balanced(tex, "\\title[RG-SCSO for Parsimonious Feature Selection]{")
    title = re.sub(r"\s+", " ", title).strip()
    abstract = _balanced(tex, "\\abstract{").strip()
    keywords_raw = _balanced(tex, "\\keywords{")
    keywords = [k.strip() for k in re.sub(r"\s+", " ", keywords_raw).split(",") if k.strip()]

    # --- body: from after \maketitle to before \bibliography ----------
    body = tex[tex.index("\\maketitle") + len("\\maketitle") : tex.index("\\bibliography{references}")]
    body = body.strip("\n")
    # The master is two-column (sn-jnl), so wide floats are starred to span both
    # columns. ASOC is single-column (elsarticle): un-star them.
    body = (body.replace("\\begin{figure*}", "\\begin{figure}")
                .replace("\\end{figure*}", "\\end{figure}")
                .replace("\\begin{table*}", "\\begin{table}")
                .replace("\\end{table*}", "\\end{table}"))
    # Journal-standard float placement: figures/tables go to the top or bottom of
    # a page ([!tbp]), never mid-paragraph. Directional reference words
    # ("below"/"above") are removed from the prose (see the generator) so a
    # floated table/figure never contradicts its reference.
    body = (body.replace("[htbp]", "[!tbp]")
                .replace("[htb]", "[!tbp]")
                .replace("[hbtp]", "[!tbp]")
                .replace("\\begin{table}[t]", "\\begin{table}[!tbp]")
                .replace("\\begin{table}[tb]", "\\begin{table}[!tbp]")
                .replace("\\begin{figure}[t]", "\\begin{figure}[!tbp]"))

    preamble = r"""% !TeX program = pdflatex
%=======================================================================
% RG-SCSO, Elsevier (elsarticle) format, target: Applied Soft Computing.
% Generated by make_asoc.py from the authoritative RG-SCSO_IJCS.tex body
% (identical content; only the class/frontmatter/bibliography differ).
%=======================================================================
\documentclass[preprint,3p,times]{elsarticle}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{algorithm}
\usepackage{algorithmic}
\usepackage{graphicx}
\graphicspath{{figures/}{./}}
\usepackage{float}
\usepackage{booktabs}
\usepackage{multirow}
\usepackage{rotating}
\usepackage{url}
\usepackage{placeins}
\usepackage{microtype}
\renewcommand{\arraystretch}{1.12}
\setlength{\emergencystretch}{3em}
% Keep inter-paragraph and around-heading spacing tight and uniform: do not let
% LaTeX stretch vertical glue to force text to the page bottom (any slack goes to
% the bottom margin instead). This removes the uneven gaps between paragraphs.
\raggedbottom

% Reduce float-induced whitespace: let floats fill more of the page before a
% text page is forced, and tighten the gaps around them.
\renewcommand{\topfraction}{0.9}
\renewcommand{\bottomfraction}{0.85}
\renewcommand{\textfraction}{0.08}
\renewcommand{\floatpagefraction}{0.75}
\setcounter{topnumber}{3}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{5}
\setlength{\textfloatsep}{10pt plus 1pt minus 1pt}
\setlength{\floatsep}{8pt plus 1pt minus 1pt}
\setlength{\intextsep}{10pt plus 1pt minus 1pt}
\setlength{\parskip}{0pt}

% On a pure float page (two stacked figures/tables), stack them from the top
% with a fixed small separation and push ALL slack to the bottom, instead of the
% default behaviour that spreads the floats apart and leaves a wide gap between
% them (e.g. between Fig. 3 and Fig. 4).
\makeatletter
\setlength{\@fptop}{0pt}
\setlength{\@fpsep}{12pt plus 0fil}
\setlength{\@fpbot}{0pt plus 1fil}
\makeatother

\newtheorem{lemma}{Lemma}
\newtheorem{proposition}[lemma]{Proposition}

\journal{Applied Soft Computing}

% Remove the "Preprint submitted to ..." footer on the first page.
\makeatletter
\def\ps@pprintTitle{%
  \let\@oddhead\@empty
  \let\@evenhead\@empty
  \let\@oddfoot\@empty
  \let\@evenfoot\@oddfoot}
\makeatother

\begin{document}

\begin{frontmatter}

\title{__TITLE__}

\author[1]{Bui Quang Huy}
\ead{huybq@donga.edu.vn}
\author[1]{Duong Minh Son}
\ead{sondm@donga.edu.vn}
\affiliation[1]{organization={Dong A University}, city={Da Nang}, country={Vietnam}}

\begin{abstract}
__ABSTRACT__
\end{abstract}

\begin{graphicalabstract}
\centering
\includegraphics[width=0.34\textwidth]{graphical_abstract.pdf}
\end{graphicalabstract}

\begin{highlights}
__HIGHLIGHTS__
\end{highlights}

\begin{keyword}
__KEYWORDS__
\end{keyword}

\end{frontmatter}
"""
    highlights = [
        "Transfer-function binarization discards swarm search detail; we name it washout",
        "RG-SCSO injects per-feature MI relevance into the binarization decision of SCSO",
        "Best mean accuracy and second-smallest subsets on 18 datasets under a fixed budget",
        "Ablation localizes the gain to the binarization step, not init or the objective",
        "Leak-free gain holds across KNN/SVM/RF wrappers; bounded on p>>n gene-expression",
    ]
    for h in highlights:
        if len(h) > 85:
            raise ValueError(f"Highlight too long ({len(h)}): {h}")
    highlights_tex = "\n".join(f"\\item {h}" for h in highlights)
    preamble = (preamble.replace("__TITLE__", title)
                        .replace("__ABSTRACT__", abstract)
                        .replace("__HIGHLIGHTS__", highlights_tex)
                        .replace("__KEYWORDS__", " \\sep ".join(keywords)))

    backmatter = r"""
\bibliographystyle{elsarticle-num}
\bibliography{references}

\end{document}
"""

    with open(OUT_TEX, "w") as fh:
        fh.write(preamble + "\n" + body + "\n" + backmatter)

    # --- supplementary: reuse IJCS supplementary (article class, journal-agnostic) ---
    supp = open(IJCS_SUPP).read()
    supp = supp.replace(
        "Supplementary Information for: Relevance-Guided",
        "Supplementary Information (Applied Soft Computing) for: Relevance-Guided",
    )
    with open(OUT_SUPP, "w") as fh:
        fh.write(supp)

    # --- Highlights (Elsevier: 3-5 bullets, <= 85 chars each) ----------
    highlights = [
        "Transfer-function binarization discards swarm search detail; we name it washout",
        "RG-SCSO injects per-feature MI relevance into the binarization decision of SCSO",
        "Best mean accuracy and second-smallest subsets on 18 datasets under a fixed budget",
        "Ablation localizes the gain to the binarization step, not init or the objective",
        "Leak-free gain holds across KNN/SVM/RF wrappers; bounded on p>>n gene-expression",
    ]
    for h in highlights:
        if len(h) > 85:
            raise ValueError(f"Highlight too long ({len(h)}): {h}")
    with open(OUT_HL, "w") as fh:
        fh.write("\n".join(highlights) + "\n")

    print(f"Wrote {OUT_TEX}, {OUT_SUPP}, {OUT_HL}")
    print(f"  title chars={len(title)}  abstract words={len(abstract.split())}  "
          f"keywords={len(keywords)}  highlights={len(highlights)} (max {max(len(h) for h in highlights)} chars)")


if __name__ == "__main__":
    build()
